accounts/urls.py
from django.urls import path

from accounts.views import (
    user_dashboard_view,
    user_login_view,
    user_logout_view,
    user_registration_view,
)

app_name = "accounts"

urlpatterns = [
    path("accounts/", user_dashboard_view, name="dashboard"),
    path("accounts/register/", user_registration_view, name="register"),
    path("accounts/login/", user_login_view, name="login"),
    path("accounts/logout/", user_logout_view, name="logout"),
]

library/urls.py
from django.urls import path

from library.views import (
    add_author_view,
    add_book_view,
    books_list_view,
    borrow_book_view,
    delete_author_view,
    delete_book_view,
)

app_name = "library"

urlpatterns = [
    path("", books_list_view, name="book-list"),
    path("add-book/", add_book_view, name="add-book"),
    path("delete-book/<uuid:id>/", delete_book_view, name="delete-book"),
    path("borrow-book/<uuid:id>/", borrow_book_view, name="borrow-book"),
    path("add-author/", add_author_view, name="add-author"),
    path("delete-author/<uuid:id>/", delete_author_view, name="delete-author"),
]

library_ms/urls.py
"""library_ms URL Configuration
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("", include("library.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from library_ms.utils import BaseModel


class User(BaseModel, AbstractUser):

    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length=255, unique=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.username

    def borrow_book(self, book):
        # import Borrow model here to avoid circular import error
        from library.models import Borrow

        borrow = Borrow.objects.create(user_id=self.id, book=book)
        borrow.save()

        return borrow

library/models.py
from django.db import models
from django.utils import timezone

from accounts.models import User
from library_ms.utils import BaseModel


class Author(BaseModel):

    full_name = models.CharField(max_length=255)
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.full_name


class Book(BaseModel):

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    cover = models.ImageField()
    title = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=True)
    publication_date = models.DateField(null=True)

    def __str__(self):
        return f"{self.title} - {self.author.full_name}"


class Borrow(BaseModel):

    # default borrow duration is 14 days / 1 week
    # if the default duration should be changed, re-run db migrations

    BORROW_DURATION = timezone.timedelta(weeks=1)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    has_returned = models.BooleanField(default=False)
    borrow_duration = models.DurationField(default=BORROW_DURATION)

    def __str__(self):
        return self.user.username

    @property
    def return_date(self):
        return self.created + self.borrow_duration

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _

from accounts.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email"]
        labels = {
            "username": _("Username"),
            "email": _("E-Mail"),
        }


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

library/forms.py
from django import forms

from library.models import Author, Book


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        exclude = ["id"]


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ["id"]

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from accounts.forms import UserLoginForm, UserRegisterForm
from library.models import Borrow


@login_required
def user_dashboard_view(request):
    borrowed_books = Borrow.objects.filter(user=request.user)
    context = {"user": request.user, "borrowed_books": borrowed_books}

    return render(request, "accounts/dashboard.html", context)


def user_registration_view(request):
    if request.method == "POST":
        registration_form = UserRegisterForm(request.POST)
        if registration_form.is_valid():
            registration_form.save()
        else:
            messages.error(request, registration_form.errors)

            return redirect("accounts:register")
    else:
        registration_form = UserRegisterForm()

    context = {"registration_form": registration_form}

    return render(request, "accounts/register.html", context)


def user_login_view(request):
    if request.method == "POST":
        login_form = UserLoginForm(request, request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get("username")
            password = login_form.cleaned_data.get("password")

            user = authenticate(username=username, password=password)

            login(request, user)

            next_url = request.GET.get("next")
            if next_url:
                return redirect(next_url)

            return redirect("accounts:dashboard")
        else:
            messages.error(request, login_form.errors)

            return redirect("accounts:login")
    else:
        login_form = UserLoginForm()

    context = {"login_form": login_form}

    return render(request, "accounts/login.html", context)


def user_logout_view(request):
    logout(request)

    return redirect("accounts:dashboard")

library/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from library.models import Author, Book
from library.forms import AuthorForm, BookForm


def books_list_view(request):
    books_queryset = Book.objects.order_by("-updated")

    context = {"books": books_queryset}

    return render(request, "library/books-list.html", context)


@login_required
def add_book_view(request):
    if request.method == "POST":
        add_book_form = BookForm(request.POST, request.FILES)

        if add_book_form.is_valid():
            add_book_form.save()

            messages.success(request, "Book has been added")

            return redirect("library:add-book")
    else:
        add_book_form = BookForm()

    context = {"add_book_form": add_book_form}

    return render(request, "library/add-book.html", context)


@login_required
def delete_book_view(request, id):
    book = get_object_or_404(Book, id=id)
    book.delete()

    messages.info(request, f"{book.title} has been deleted")

    return redirect("library:book-list")


@login_required
def borrow_book_view(request, id):
    user = request.user

    book = get_object_or_404(Book, id=id)
    user.borrow_book(book)

    messages.success(request, f"You just borrowed {book.title}")

    return redirect("library:book-list")


@login_required
def add_author_view(request):
    if request.method == "POST":
        add_author_form = AuthorForm(request.POST)

        if add_author_form.is_valid():
            add_author_form.save()

            messages.success(request, "Author has been added")

            return redirect("library:add-author")
    else:
        add_author_form = AuthorForm()

    context = {"add_author_form": add_author_form}

    return render(request, "library/add-author.html", context)


@login_required
def delete_author_view(request, id):
    author = get_object_or_404(Author, id=id)
    author.delete()

    messages.info(request, f"{author.full_name} has been deleted")

    return redirect("library:book-list")

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block title %} User Dashboard {% endblock title %}

{% block content %}
<h1 class="text-white">Welcome, {{ user.username }}</h1>

<div class="grid sm:grid-cols-4 grid-rows-1 mx-auto gap-4 p-2 w-fit">
    {% for book in borrowed_books %}
        {% include 'components/borrowed-book-card.html' %}
    {% endfor %}
</div>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
User Login
{% endblock title %}

{% block body %}
    {% block content %}
    <form method="POST">
        {% csrf_token %}

        {% with form=login_form %}
            {% include 'components/form-renderer.html' %}
        {% endwith %}

        <button>Login</button>

        <a class="text-gray-400 hover:underline" href="{% url 'accounts:register' %}">register here</a>
    </form>
    {% endblock content %}
{% endblock body %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}User Registration{% endblock title %}

{% block body %}
    {% block content %}
    <form method="POST">
        {% csrf_token %}

        {% with form=registration_form %}
            {% include 'components/form-renderer.html' %}
        {% endwith %}

        <button class="px-4 py-2 bg-gray-900 text-white">Register</button>

        <a class="text-gray-400 hover:underline" href="{% url 'accounts:login' %}">login here</a>
    </form>
    {% endblock content %}
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>

    <title>
      {% block title %}Library Management System{% endblock title %}
    </title>
  </head>
  <body>
    {% block body %}
      <div class="h-screen">
        {% include 'components/navbar.html' %}

        <main class="z-10">
          <div>
            {% if messages %}
              {% for message in messages %}
                  {% include 'components/messages.html' %}
              {% endfor %}
            {% endif %}
          </div>
  
          <div class="container mx-auto py-4 h-full">
            {% block content %}
            {% endblock content %}
          </div>
        </main>
      </div>
    {% endblock body %}
  </body>
</html>

templates/components/book-card.html
{% load static %}
<div class="bg-gray-800 text-white p-2 w-fit h-fit relative">
    <div class="flex flex-row items-center justify-center gap-2 group">
        <div>
            <img src="{{ book.cover.url }}" alt="{{ book.title }}" class="object-fit h-10 w-10 sm:md:group-hover:rounded-none rounded-full transition-all duration-[500ms] group-hover:scale-[current] sm:md:group-hover:scale-[10] group-hover:static sm:md:group-hover:fixed top-[40%] right-[50%] group-hover:z-20 transform">
        </div>
    
        <div>
            <p>{{ book.title }}</p>
            <small>{{ book.author.full_name }}</small>
            <small>on <i>{{ book.publication_date }}</i></small>
        </div>
    </div>

    <div>
        <small class="text-gray-300">
            updated {{ book.updated|timesince }} ago
        </small>
    </div>

    <div class="flex flex-row gap-2">
        <a href="{% url 'library:borrow-book' book.id %}">
            <button title="Borrow book">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>
            </button>
        </a>

        <a href="{% url 'library:delete-book' book.id %}">
            <button title="Delete book" class="bg-red-600">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
            </button>
        </a>
    </div>
</div>

templates/components/book-list-toolbar.html
<div class="flex flex-row justify-between items-center z-0 px-4">
    <div>
        <p class="text-white">Books / {{ action }}</p>
    </div>
    <div>
        <a href="{% url 'library:add-book' %}">
            <button class="bg-gray-900 text-white px-4 py-2">
                Add Book
            </button>
        </a>
    </div>
</div>

templates/components/borrowed-book-card.html
{% load static %}
<div class="bg-gray-800 text-white p-2 w-fit h-fit relative">
    <div class="flex flex-row items-center justify-center gap-2 group">
        <div>
            <img src="{{ book.book.cover.url }}" alt="{{ book.title }}" class="object-fit h-10 w-10 sm:md:group-hover:rounded-none rounded-full transition-all duration-[500ms] group-hover:scale-[current] sm:md:group-hover:scale-[10] group-hover:static sm:md:group-hover:fixed top-[40%] right-[50%] group-hover:z-20 transform">
        </div>
    
        <div>
            <p>{{ book.book.title }}</p>
            <small>{{ book.book.author.full_name }}</small>
            <small>on <i>{{ book.book.publication_date }}</i></small>
        </div>
    </div>

    <div>
        <small class="text-gray-300">
            borrowed {{ book.created|timesince }} ago
        </small>
    </div>

    <div class="flex flex-row gap-2">
        <a href="{% url 'library:borrow-book' book.id %}">
            <button title="Borrow book">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>
            </button>
        </a>

        <small>
            You should return this book by {{ book.return_date|date:"ga jS M, Y" }}
        </small>
    </div>
</div>

templates/components/form-renderer.html
{% for form in form %}
    <div>
        <label for="{{ form.id_for_label }}" class="text-left text-white block">
            {{ form.label }}
        </label>

        {% if form.widget_type == "select" %}
            <select name="{{ form.name }}" id="{{ form.id_for_label }}" class="p-2">
                <option disabled>{{form.label}}</option>
                {% for value, text in form.field.choices %}
                    <option value="{{ value }}">{{ text }}</option>
                {% endfor %}
            </select>
        {% elif form.widget_type == "textarea" %}
            <textarea name="{{ form.name }}" id="{{ form.id_for_label }}" cols="30" rows="10" class="p-2"></textarea>
        {% elif form.widget_type == "clearablefile" %}
            <input type="file" name="{{ form.name }}" id="{{ form.id_for_label }}">
        {% else %}
            <input class="p-2" id="{{ form.id_for_label }}" type="{{ form.widget_type }}" name="{{ form.name }}" >
        {% endif %}
    </div>
{% endfor %}

templates/components/messages.html
<div class="bg-indigo-600">
    <div class="max-w-7xl mx-auto py-3 px-3 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between flex-wrap">
        <div class="w-0 flex-1 flex items-center">
          <span class="flex p-2 rounded-lg bg-indigo-800">
            <!-- Heroicon name: outline/speakerphone -->
            <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
            </svg>
          </span>
          <p class="ml-3 font-medium text-white truncate">
            <span class="md:hidden">
              Something you should know about ...
            </span>

            <span class="hidden md:inline text-white">
                {{ message|safe }}
            </span>
          </p>
        </div>

        <div class="order-2 flex-shrink-0 sm:order-3 sm:ml-3">
          <button type="button" class="-mr-1 flex p-2 rounded-md hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-white sm:-mr-2">
            <span class="sr-only">Dismiss</span>
            <!-- Heroicon name: outline/x -->
            <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>

templates/components/navbar.html
<!-- This example requires Tailwind CSS v2.0+ -->
<nav class="bg-gray-800 sticky top-0 shadow-lg z-10">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16"> 
      <div
        class="flex-1 flex items-center justify-start"
      >
        <a class="flex-shrink-0 gap-2 flex items-center" href="/">
          <img
            class="h-8 w-auto inline"
            src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg"
            alt="Workflow"
          />
          <span class="inline text-white font-medium">Library MS</span>
        </a>

        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a
              href="{% url 'accounts:dashboard' %}"
              class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium"
              aria-current="page"
              >Dashboard</a
            >

            <a
              href="{% url 'library:book-list' %}"
              class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
              >Books</a
            >

            <a
              href="#"
              class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
              >Authors</a
            >
          </div>
        </div>
      </div>
      <div
        class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0"
      >
        <button
          type="button"
          class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
        >
          <span class="sr-only">View notifications</span>
          <!-- Heroicon name: outline/bell -->
          <svg
            class="h-6 w-6"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-hidden="true"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
            />
          </svg>
        </button>
        
        {% if user %}
            <!-- Profile dropdown -->
            <div class="ml-3 relative">
            <div>
                <button
                type="button"
                class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white p-0"
                id="user-menu-button"
                aria-expanded="false"
                aria-haspopup="true"
                onclick="toggle_menu('menu')"
                >
                <span class="sr-only">Open user menu</span>
                <img
                    class="h-8 w-8 rounded-full"
                    src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                    alt=""
                />
                </button>
            </div>

            <!--
                Dropdown menu, show/hide based on menu state.
    
                Entering: "transition ease-out duration-100"
                    From: "transform opacity-0 scale-95"
                    To: "transform opacity-100 scale-100"
                Leaving: "transition ease-in duration-75"
                    From: "transform opacity-100 scale-100"
                    To: "transform opacity-0 scale-95"
                -->
            <div
                class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none transform opacity-0 scale-0 transition duration-[600ms]"
                role="menu"
                aria-orientation="vertical"
                aria-labelledby="user-menu-button"
                tabindex="-1"
                id="menu"
            >
                <!-- Active: "bg-gray-100", Not Active: "" -->
                <a
                  href="#"
                  class="block px-4 py-2 text-sm text-gray-700"
                  role="menuitem"
                  tabindex="-1"
                  id="user-menu-item-0"
                  >Your Profile</a>
                <a
                href="#"
                class="block px-4 py-2 text-sm text-gray-700"
                role="menuitem"
                tabindex="-1"
                id="user-menu-item-1"
                >Settings</a
                >
                <a
                href="#"
                class="block px-4 py-2 text-sm text-gray-700"
                role="menuitem"
                tabindex="-1"
                id="user-menu-item-2"
                >Sign out</a
                >
            </div>
            </div>
        {% else %}
        <a
        href="{% url 'accounts:login' %}"
        class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
        >Login</a
      >
        {% endif %}
      </div>
    </div>
  </div>
</nav>

templates/library/add-author.html
{% extends 'base.html' %}

{% block title %}Add Author{% endblock title %}

{% block content %}
    <form method="POST">
        {% csrf_token %}

        {% with form=add_author_form %}
            {% include 'components/form-renderer.html' %}
        {% endwith %}

        <button>Add Author</button>
    </form>
{% endblock content %}

templates/library/add-book.html
{% extends 'base.html' %}

{% block title %}Add Book{% endblock title %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% with form=add_book_form %}
            {% include 'components/form-renderer.html' %}
        {% endwith %}

        <button>Add Book</button>
    </form>
{% endblock content %}

templates/library/books-list.html
{% extends 'base.html' %}

{% block content %}
    {% with action="List" %}
        {% include 'components/book-list-toolbar.html' %}
    {% endwith %}

    <div class="grid sm:grid-cols-4 grid-rows-1 mx-auto gap-4 p-2 w-fit">
        {% for book in books %}
            {% include 'components/book-card.html' %}
        {% endfor %}
    </div>
{% endblock content %}